version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  db:
    image: postgres:alpine
    container_name: postgres
    environment:
      - POSTGRES_DB=netology_stocks_products
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=5728821q
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -u postgres -d netology_stocks_products"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  pg_admin:
      image: dpage/pgadmin4:latest
      container_name: pgadmin
      deploy:
        resources:
          limits:
            cpus: '0.1'
            memory: 2G
      ports:
        - '8000:80'
      environment:
        PGADMIN_DEFAULT_EMAIL: admin1@mail.com
        PGADMIN_DEFAULT_PASSWORD: 5728821q
        PGADMIN_CONFIG_SERVER_MODE: 'False'
      networks: 
        - app-network

  backend:
    build: .
    container_name: my_app
    networks:
      - app-network
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:5728821q@db:5432/netology_stocks_products
    command: >
      sh -c "python manage.py migrate && gunicorn --bind 0.0.0.0:8000 stocks_products.wsgi:application"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '8001:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - backend
